# pytest.ini
[pytest]
addopts =
    -ra -q
    --tb=short
    --maxfail=1
    -n auto
    --alluredir=reports\allure-results
    --html=reports\pytest\report.html
    --self-contained-html

markers =
    smoke: quick critical checks
    regression: full suite
    esg: ESG flow tests

# Show extra metadata in pytest-html
metadata =
    Project  = Selenium_Framework_Python_Automation
    Platform = Windows